### PR TITLE
Test 2

### PR DESCRIPTION
**Pull request by Greg-Smulko**

### CODE REVIEW

**Review by TheEadie — COMMENTED** [review]
Hmmm is it the right level of test though? :drive-by: non-commital review

**Review by TheEadie — CHANGES_REQUESTED** [review]
Needs moar tests

**Review by Greg-Smulko — COMMENTED** [review]
You can also push to this branch @TheEadie and see what happens. (or we can create a separate PR for that)

**Review by TheEadie — APPROVED** [review]
OK maybe 2 tests is enough

**Pull request merged**
